### ISSUE TITLE
Finish Pool implementation

### ISSUE THREAD

**Issue by krtek4** [functional-php/trampoline#1]
- [x] Basic Pool implementation
- [x] Documentation
- [x] Make it work for any callable not only Closures on PHP 7.1
- [x] release new version

Based on https://gist.github.com/beberlei/4145442

Another option would be to get rid of the class alltogether and force the user to implement the recursion himself, see https://github.com/lstrojny/functional-php/pull/109

**Comment by pyldin601** [comment]
As you promote fp, I think it would be cool if you implement tail rec without classes :)

**Comment by krtek4** [comment]
Classes can be used like functions without any hassle. Anonymous functions are even instances of the `Closure` class in the engine. Do you know of any downside using a class with an `__invoke` method compared to a more "traditional" anonymous function ?

PHP not being really good at functional programming, I think it is better to make do with what is available instead of dogmatically refuse to use classes.

I saw you implementation on the linked issue, the reason I used a class is because I think using `$this` for the continuation like I am doing is cleaner than have to pass the function by reference using `use`. But this is more of a personal preference.

Your implementation has the advantage to work with any `callable` and not only `Closure` instances as is the case of mine for now. This is why I am considering using only a function. I need to think this through.

Thanks for your feedback !

**Comment by pyldin601** [comment]
Yes I understand you. But I frequently use `$this` inside callables as handle to current object. So that is because I reworked [this](https://gist.github.com/beberlei/4145442) solution to have no side effects outside wrapper and do not change behavior of wrapped callables.
